server
{
  listen 80;
  underscores_in_headers on;

  location ~ ^/([a-zA-Z0-9-]+)(/.*)?$ {
    alias /var/web/livelihood-ui;
    index index.html index.htm;
    try_files $2 /index.html;
  }

  location / {
    root /var/web/livelihood-ui;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
}
