name: livelihood
description: "Livelihood Field Assist UI starter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.3.0
  badges: 3.1.2
  camera: 0.11.0+2
  cached_network_image: ^3.4.0
  connectivity_plus: ^6.0.3
  digit_scanner: 1.0.6+4
  digit_forms_engine: 0.0.9-dev
  digit_ui_components: 0.2.3+1
  dio: ^5.4.3+1
  file_picker: 8.0.7
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_bloc: 8.1.6
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: 1.4.1+1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.1
  google_mlkit_barcode_scanning: 0.12.0
  http_parser: ^4.0.2
  image_picker: 1.1.2
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.7.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  mime: ^1.0.6
  path: ^1.9.0
  path_provider: ^2.1.0
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  reactive_forms: ^17.0.0
  shared_preferences: ^2.2.3
  synchronized: ^3.1.0+1
  video_player: ^2.9.5
  webview_flutter: ^4.8.0

dependency_overrides:
  camera_android_camerax: ^0.5.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animated_json/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf
