[project]
name = "ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "kafka-python>=2.2.15",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.1",
    "python-json-logger>=3.3.0",
    "python-multipart>=0.0.20",
    "qrcode>=8.2",
    "requests>=2.32.4",
    "uvicorn>=0.35.0",
    "fastapi-health>=0.4.0",
    "greenlet>=3.2.4",
    "pillow>=11.3.0",
    "psycopg>=3.2.9",
    "pypdf>=4.0.0",
    "sqlalchemy>=2.0.43",
]
